name: apiverve_chucknorris
description: Chuck Norris Jokes is a simple tool for getting Chuck Norris jokes. It returns a random Chuck Norris joke.
version: 1.1.14
homepage: https://apiverve.com/marketplace/chucknorris?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/chucknorris-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
